### ISSUE TITLE
Campo opcional 'Aliquota' não está disponível para ser informado.

### ISSUE THREAD

**Issue by guilherme737** [nfephp-org/sped-nfse-amtec#11]
No documento de referência para integração da NFS-e de Goiânia tem a seguinte observação:

> A tag alíquota será obrigatória apenas quando o Prestador é enquadrado no Simples Nacional. Nas demais situações essa informação não é obrigatória e será gerada pelo sistema.

No entanto a opção não está disponível na lib quando é necessário utilizá-la. 

Acredito que a solução seria apenas adicionar o seguinte código no arquivo **Factory.php**:
```php
    $this->dom->addChild(
            $valnode,
            "Aliquota",
            isset($val->aliquota)
                ? number_format($val->aliquota, 2, '.', '')
                : null,
            false
        );
```
logo após o local que adiciona o **ValorCsll**.

Para o momento fiz essa alteração localmente e resolveu, a sugestão é para que seja adicionado na lib tratando como um valor opcional, enviada apenas se for informada.

**Comment by robmachado** [comment]
Opa ! Guilherme, obrigado
Essa API é complicada mesmo tem pouca ou quase nenhuma documentação estou refatorando.

**Comment by robmachado** [comment]
Haviam ainda outros erros que acredito ter corrigido.
Por favor teste e me informe dos resultados !

**Comment by guilherme737** [comment]
Boas Roberto, passei a issue porque percebi q seria coisa simples e vai ajudando a aperfeiçoar, vlws.

**Comment by robmachado** [comment]
Guilherme, faça isso SEMPRE me ajuda muito :+1:
