### ISSUE TITLE
Call to undefined function Safe\sprintf()

### ISSUE THREAD

**Issue by josetiagobispo** [nfephp-org/sped-nfse-amtec#14]
Estou obtendo o seguinte erro ao gerar uma RPS estou utilizando o Lumen do Laravel.
Call to undefined function Safe\sprintf() in Rps.php line 109

**Comment by josetiagobispo** [comment]
Alterei a linha Rps.php line 109 para print_r , exibiu os erros :

  | Array
-- | --
  | (
  | [property] => naturezaoperacao
  | [pointer] => /naturezaoperacao
  | [message] => The property naturezaoperacao is required
  | [constraint] => required
  | [context] => 1
  | )
  | Array
  | (
  | [property] => regimeespecialtributacao
  | [pointer] => /regimeespecialtributacao
  | [message] => The property regimeespecialtributacao is required
  | [constraint] => required
  | [context] => 1
  | )
  | Array
  | (
  | [property] => optantesimplesnacional
  | [pointer] => /optantesimplesnacional
  | [message] => The property optantesimplesnacional is required
  | [constraint] => required
  | [context] => 1
  | )
  | Array
  | (
  | [property] => incentivadorcultural
  | [pointer] => /incentivadorcultural
  | [message] => The property incentivadorcultural is required
  | [constraint] => required
  | [context] => 1
  | )
  | Array
  | (
  | [property] => status
  | [pointer] => /status
  | [message] => The property status is required
  | [constraint] => required
  | [context] => 1
  | )

**Comment by robmachado** [comment]
O pacote \Safe não está instalado em produção ...
Está errado o composer.json .. o pacote abaixo deve estar no bloco require e não em require-dev

"thecodingmachine/phpstan-safe-rule": "^0.1.2",

Estou corrigindo

**Comment by josetiagobispo** [comment]
muito obrigado, acabei de descobrir isso https://github.com/thecodingmachine/safe só incluir o pacote no json. muito obrigado pela resposta.
